### ISSUE TITLE
pre-install the endpoint pubkey in known_hosts

### ISSUE THREAD

**Issue by nicolasochem** [midl-dev/tezos-remote-signer-os#17]
When provisioning a signer, it is necessary to ssh once to the endpoint then type "yes". Remove this step by populating the endpoint sshd pubkey in ~/.ssh/known_hosts

**Comment by puppetninja** [comment]
implemented by
https://github.com/midl-dev/tezos-remote-signer-os/commit/e4e98fa41d5401e372c324ed0dba0d5307d38122
