### ISSUE TITLE
Download compiled binaries instead compiling Tezos

### ISSUE THREAD

**Issue by marianogadea** [midl-dev/tezos-remote-signer-os#5]
Hi, now as of version 8.1 binaries can be download without the need to compile the full application and I think this will improve the build time for the remote signer.
Binaries can be found here: https://gitlab.com/tezos/tezos/-/releases/8.1.0

**Comment by denver-s** [comment]
[Related comment](https://github.com/midl-dev/tezos-remote-signer-os/issues/2#issuecomment-751986844).

The "problem" is that Gitlab requires an API token in order to download.

**Comment by denver-s** [comment]
Or, if possible, add the binary file(s) to this repository.

**Comment by marianogadea** [comment]
isn't possible to add the token to the manifest, or take it from a vault?

**Comment by nicolasochem** [comment]
I just tried with this repo instead
https://github.com/serokell/tezos-packaging

But it is 64 bit arm, while raspbian is still 32 bit, so it's not suitable unfortunately. Hopefully raspbian moves to 64 bit by default soon.

**Comment by nicolasochem** [comment]
This is now fixed with the migration to ubuntu.
